fix: review

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -52,7 +52,8 @@ jobs:
       - run: yarn install --frozen-lockfile --non-interactive
 
       - name: Run tests
-        run: yarn test:prod
+        # Try yarn test:prod up to three times, if it fails and exit with the exit code from the last execution
+        run: for i in $(seq 1 3); do [ $i -gt 1 ] && sleep 5; yarn test:prod && s=0 && break || s=$?; done; (exit $s)
         env:
           NODE_OPTIONS: '--max-old-space-size=6144'
       - name: Store coverage
