build: retry tests up to 2 times if they fail (#1751)

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -45,7 +45,8 @@ jobs:
         uses: ./.github/actions/yarn-install
 
       - name: Run tests
-        run: yarn test:prod
+        # Try yarn test:prod up to three times, if it fails and exit with the exit code from the last execution
+        run: for i in $(seq 1 3); do [ $i -gt 1 ] && sleep 5; yarn test:prod && s=0 && break || s=$?; done; (exit $s)
       - name: Store coverage
         if: github.event_name == 'pull_request'
         uses: actions/upload-artifact@v3
